// Consider standard collections stable, as we replace them entirely in UiState
kotlin.collections.List
kotlin.collections.Map
kotlin.collections.Set

// Consider time classes stable
java.time.LocalTime
java.time.LocalDate
java.util.Calendar
java.util.TimeZone
